#!/bin/bash

if [[ ! -e /app/logs ]]; then
    mkdir -p /app/logs
fi

DATE=$(date --rfc-3339=seconds)
STDOUT_FILE=/app/logs/app-stdout.log
STDERR_FILE=/app/logs/app-stderr.log

function print_banner () {
  cat >> $1 <<EOF
     =======================
 ===============================
=== Process started at:       ===
=== ${DATE} ===
 ===============================
     =======================
EOF
}

print_banner ${STDOUT_FILE}
print_banner ${STDERR_FILE}

exec /app/ultralisp-server \
        >> ${STDOUT_FILE} \
        2>> ${STDERR_FILE}

