version: '3.7'
services:
  app:
    extends:
      file: common-services.yml
      service: app
    depends_on:
      - postgres
      - elastic
      - worker
      - lw_worker
      - gearman
  gearman:
    extends:
      file: common-services.yml
      service: gearman
  worker:
    extends:
      file: common-services.yml
      service: worker
    depends_on:
      - postgres
      - elastic
      - gearman
  lw_worker:
    container_name: ultralisp_lw_worker
    build:
      context: .
      target: lw-worker
    restart: always
    ports:
      - "127.0.0.1:14007:4005"
    volumes:
      - ./app.asd:/app/app.asd
      - ./app-deps.asd:/app/app-deps.asd
      - ./quicklisp/local-projects:/app/quicklisp/local-projects
      - ./src/:/app/src/
      - ./roswell/:/app/roswell/
      - ./logs/:/app/logs/
      - ./new-libs/:/app/new-libs/
      - ./build/:/app/build/
      - ./lw/:/lw/
    depends_on:
      - postgres
      - elastic
      - gearman
    environment:
      DEBUG: 1
      MODE: worker
      ELASTIC_HOST: elastic
      GEARMAN_SERVER: gearman:4730
  postgres:
    extends:
      file: common-services.yml
      service: postgres
  elastic:
    extends:
      file: common-services.yml
      service: elastic
  empty-postgres:
    extends:
      file: common-services.yml
      service: empty-postgres
  gen-deps-system:
    extends:
      file: common-services.yml
      service: gen-deps-system
  mito:
    extends:
      file: common-services.yml
      service: mito
    depends_on:
      - postgres
      - empty-postgres
  db-ops:
    extends:
      file: common-services.yml
      service: db-ops
    depends_on:
      - postgres
