#!/bin/bash

/app/worker \
        --interface "0.0.0.0" \
        --port "10100" \
        --one-task-only \
        --slynk-interface "0.0.0.0" \
        --slynk-port "4005" \
        | tee -a /app/logs/worker-1.log \
        | jsail
