#!/bin/bash

set -Eeuo pipefail

if [[ ! -e /app/logs ]]; then
    mkdir -p /app/logs
fi

DATE=$(date --rfc-3339=seconds)

LICENSE_FILE=/lw/license
APPLIED_LICENSE_FILE=/usr/local/lib64/LispWorks/lib/8-1-0-0/config/lwlicense

STDOUT_FILE=/app/logs/lw-worker-stdout.log
STDERR_FILE=/app/logs/lw-worker-stderr.log

function print_banner () {
  cat >> $1 <<EOF
     =======================
 ===============================
=== Process started at:       ===
=== ${DATE} ===
 ===============================
     =======================
EOF
}

print_banner ${STDOUT_FILE}
print_banner ${STDERR_FILE}


if [[ ! -e ${APPLIED_LICENSE_FILE} ]] || ! grep -q $(hostname) ${APPLIED_LICENSE_FILE}; then
    if [[ -e ${LICENSE_FILE} ]]; then
        echo 'Applying LispWorks license.' >> ${STDOUT_FILE}
        lispworks $(cat ${LICENSE_FILE}) >> ${STDOUT_FILE} 2>&1
        
        echo 'License was successfully applied:' >> ${STDOUT_FILE}
        grep -e '###' -e 'SERIAL' -e 'EXPIRATION' ${APPLIED_LICENSE_FILE} >> ${STDOUT_FILE}
    else
        echo "ERROR: There is no license for current host $(hostname) and no license file ${LICENSE_FILE}." >> ${STDOUT_FILE}
        sleep 60s
        exit 1
    fi
else
    echo 'Found a LispWorks license.' >> ${STDOUT_FILE}
fi


if [[ -e ${LICENSE_FILE} ]]; then
   echo "Removing ${LICENSE_FILE} file" >> ${STDOUT_FILE}
   rm ${LICENSE_FILE}
fi

exec /app/worker \
        --one-task-only \
        --slynk-interface "0.0.0.0" \
        --slynk-port "4005" \
        --debug \
        >> ${STDOUT_FILE} \
        2>> ${STDERR_FILE}
