#!/bin/bash

if [[ ! -e /app/logs ]]; then
    mkdir -p /app/logs
fi

DATE=$(date --rfc-3339=seconds)

function print_banner () {
  cat >> $1 <<EOF
     =======================
 ===============================
=== Process started at:       ===
=== ${DATE} ===
 ===============================
     =======================
EOF
}

print_banner /app/logs/lw-worker-stdout.log
print_banner /app/logs/lw-worker-stderr.log


if [[ ! -e /usr/local/lib64/LispWorks/lib/8-0-0-0/config/lwlicense ]] || ! grep -q $(hostname) /usr/local/lib64/LispWorks/lib/8-0-0-0/config/lwlicense; then
    if [[ -e /lw/license ]]; then
        echo 'Applying LispWorks license.' >> /app/logs/lw-worker-stdout.log
        /usr/local/lib64/LispWorks/lispworks-8-0-0-amd64-linux $(cat /lw/license)
        
        echo 'License was successfully applied:'
        grep -e '###' -e 'SERIAL' -e 'EXPIRATION' /usr/local/lib64/LispWorks/lib/8-0-0-0/config/lwlicense

        echo 'Removing /lw/license file'
        rm /lw/license
    else
        echo "WARN: There is no license for current host $(hostname) and file in /lw/license." >> /app/logs/lw-worker-stdout.log
    fi
else
    echo 'Found an LispWorks license.' >> /app/logs/lw-worker-stdout.log
fi

/app/worker \
        --one-task-only \
        --slynk-interface "0.0.0.0" \
        --slynk-port "4005" \
        --debug \
        >> /app/logs/lw-worker-stdout.log \
        2>> /app/logs/lw-worker-stderr.log
